name: CI/CD Chinook
on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pytest --cov=app -v
        env:
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: localhost
          DB_PORT: "3306"
          DB_NAME: chinook

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci && npm run test

  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: echo "~/start_backend.sh" | at now

  deploy-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: echo "~/start_frontend.sh" | at now
